# The Site Configuration

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# --------------------------
theme: jekyll-theme-chirpy
title: devkwonms                          # the main title

tagline: Langsam aber sicher   # it will display as the sub-title

description: 코린이                  # used by seo meta and the atom feed
 

# fill in the protocol & hostname for your site, e.g., 'https://username.github.io'
url: 'https://devkwonms.github.io'

author: devkwonms                  # change to your full name

github:
  username: devkwonms             # change to your github username

instagram:
  username:            # change to your twitter username

social:
  name: Kwon Min Seo                  # it will shows as the copyright owner in Footer
  email: devkwonms@nate.com            # change to your email address
  links:
    # The first element serves as the copyright owner's link
    - https://github.com/devkwonms      # change to your github homepage
#     - https://www.instagram.com/doongram_/      # change to your twitter homepage
    # Uncomment below to add more social links
    # - https://www.facebook.com/username
    # - https://www.linkedin.com/in/username

google_site_verification: # change to your verification string
# --------------------------


# Only if your site type is GitHub Project sites and doesn't have a custom domain,
# change below value to '/projectname'.
baseurl: ''

# Change to your timezone › http://www.timezoneconverter.com/cgi-bin/findzone/findzone
timezone: Asia/Seoul

google_analytics:
  id: ''          # Fill with your Google Analytics ID
  pv:
    # The Google Analytics pageviews switch.
    # DO NOT enable it unless you know how to deploy the Google Analytics superProxy.
    enabled: false
    # the next options only valid when `google_analytics.pv` is enabled.
    proxy_url: ''
    proxy_endpoint: ''
    cache: false  # pv data local cache, good for the users from GFW area.

# disqus:
#   comments: true  # boolean type, the global switch for posts comments.
#   shortname: ''    # Fill with your Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname


# Prefer color scheme setting.
#
# Note: Keep empty will follow the system prefer color by default,
# and there will be a toggle to switch the theme between dark and light
# on the bottom left of the sidebar.
#
# Available options:
#
#     light  - Use the light color scheme
#
#     dark   - Use the dark color scheme
#
theme_mode: dark  # [light|dark]

# The CDN endpoint for images.
# Notice that once it is assigned, the CDN url
# will be added to all image (site avatar & posts' images) paths starting with '/'
#
# e.g. 'https://cdn.com'
img_cdn: ''

# the avatar on sidebar, support local or CORS resources
avatar: https://avatars.githubusercontent.com/u/77871140?v=4


# boolean type, the global switch for ToC in posts.
toc: true
# <script src="https://giscus.app/client.js"
#         data-repo="devkwonms/devkwonms.github.io"
#         data-repo-id="R_kgDOHaCh1Q"
#         data-category="[ENTER CATEGORY NAME HERE]"
#         data-category-id="[ENTER CATEGORY ID HERE]"
#         data-mapping="pathname"
#         data-reactions-enabled="1"
#         data-emit-metadata="0"
#         data-input-position="bottom"
#         data-theme="dark"
#         data-lang="ko"
#         crossorigin="anonymous"
#         async>
# </script>
comments:
  active: 'giscus'        # The global switch for posts comments, e.g., 'disqus'.  Keep it empty means disable
  # The active options are as follows:
  disqus:
    shortname: braveleftji-github-io   # fill with the Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  # utterances settings › https://utteranc.es/
  utterances:
    repo: 'Braveleftji/braveleftji.github.io'         # <gh-username>/<repo>
    issue_term: 'pathname'  # < url | pathname | title | ...>
  # Giscus options › https://giscus.app
  giscus:
    repo: 'devkwonms/devkwonms.github.io'            # <gh-username>/<repo>
    repo_id: 'R_kgDOHaCh1Q'
    category: "Announcements"
    category_id: "DIC_kwDOHaCh1c4CPVBI"
    mapping:          # optional, default to 'pathname'
    input_position:   # optional, default to 'bottom'
    lang: 'ko'            # optional, default to the value of `site.lang`

# Self-hosted static assets, optional › https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    enabled:      # boolean, keep empty means false
    # specify the Jekyll environment, empty means both
    # only works if `assets.self_host.enabled` is 'true'
    env:          # [development|production]

paginate: 10

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:   # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ''          # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true    # Enable comments in posts.
      toc: true         # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ''
      type: tabs             # see `site.collections`
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/img/favicons
    values:
      swcache: true
  - scope:
      path: assets/js/dist
    values:
      swcache: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - '*.gem'
  - '*.gemspec'
  - tools
  - README.md
  - LICENSE
  - gulpfile.js
  - node_modules
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
